services:
  - type: web
    name: shopez-ecommerce
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: NEXT_PUBLIC_RAZORPAY_KEY_ID
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLOUD_VISION_KEY
        sync: false
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
